In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
telecom = pd.read_csv('E:/May 22 Logistic regression-confusion metrics/Telco-Customer-Churn.csv')

In [3]:
telecom.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
telecom.drop('customerID', axis = 1, inplace = True)

In [5]:
X=telecom.iloc[:, [1, 19]].values
y = telecom.iloc[:, -1].values

In [6]:
telecom.shape

(7043, 20)

In [7]:
telecom['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

In [8]:
telecom['gender'] = telecom.gender.replace({'Male': 1, 'Female': 2})

In [9]:
telecom['Partner'].value_counts()

No     3641
Yes    3402
Name: Partner, dtype: int64

In [10]:
telecom['Partner'] = telecom.Partner.replace({'No':1, 'Yes':0})

In [11]:
telecom['Dependents'].value_counts()

No     4933
Yes    2110
Name: Dependents, dtype: int64

In [12]:
telecom['Dependents'] = telecom.Dependents.replace({'No':1, 'Yes':0})

In [13]:
telecom['PhoneService'].value_counts()

Yes    6361
No      682
Name: PhoneService, dtype: int64

In [14]:
telecom['PhoneService'] = telecom.PhoneService.replace({'Yes':1, 'No':0})

In [15]:
telecom['MultipleLines'].value_counts()

No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

In [16]:
telecom['MultipleLines'] = telecom.MultipleLines.replace({'No':1, 'Yes':2, 'No phone service':0})

In [17]:
telecom['InternetService'].value_counts()

Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

In [18]:
telecom['InternetService'] = telecom.InternetService.replace({'Fiber optic': 1, 'DSL': 2, 'No':0})

In [19]:
telecom['OnlineSecurity'].value_counts()

No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

In [20]:
telecom['OnlineSecurity'] = telecom.OnlineSecurity.replace({'No':1, 'Yes':2, 'No internet service': 0})

In [21]:
telecom['DeviceProtection'].value_counts()

No                     3095
Yes                    2422
No internet service    1526
Name: DeviceProtection, dtype: int64

In [22]:
telecom['DeviceProtection'] = telecom.DeviceProtection.replace({'No': 1, 'Yes':2, 'No internet service':0})

In [23]:
telecom['TechSupport'].value_counts()

No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

In [24]:
telecom['TechSupport'] = telecom.TechSupport.replace({'No':1, 'Yes':2, 'No internet serice': 0})

In [25]:
telecom['StreamingTV'].value_counts()

No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

In [26]:
telecom['StreamingTV'] = telecom.StreamingTV.replace({'No':1, 'Yes':2, 'No internet service':0})

In [27]:
telecom['StreamingMovies'].value_counts()

No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

In [28]:
telecom['StreamingMovies'] = telecom.StreamingMovies.replace({'No':1, 'No': 2, 'No internet service':0})

In [29]:
telecom['Contract'].value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

In [30]:
telecom['Contract'] = telecom.Contract.replace({'Month-to-month':1, 'Two year':2, 'One year':0})

In [31]:
telecom['PaperlessBilling'].value_counts()

Yes    4171
No     2872
Name: PaperlessBilling, dtype: int64

In [32]:
telecom['PaperlessBilling'] = telecom.replace({'Yes':1, 'No':0})

In [33]:
telecom['PaymentMethod'].value_counts()

Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

In [34]:
telecom['PaymentMethod'] = telecom.PaymentMethod.replace({'Electronic check':1, 'Mailed check':2, 'Bank transfer (automatic)':3, 
                                                         'Credit card (automatic)': 0})

In [35]:
telecom['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [36]:
telecom['Churn'] = telecom.Churn.replace({'No':1, 'Yes':0})

In [37]:
telecom.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       2              0        0           1       1             0   
1       1              0        1           1      34             1   
2       1              0        1           1       2             1   
3       1              0        1           1      45             0   
4       2              0        1           1       2             1   

   MultipleLines  InternetService  OnlineSecurity OnlineBackup  \
0              0                2               1          Yes   
1              1                2               2           No   
2              1                2               2          Yes   
3              0                2               2           No   
4              1                1               1           No   

   DeviceProtection TechSupport  StreamingTV StreamingMovies  Contract  \
0                 1           1            1               2         1   
1                 2           1            1               2         0   
2                 1           1            1               2         1   
3                 2           2            1               2         0   
4                 1           1            1               2         1   

  PaperlessBilling  PaymentMethod  MonthlyCharges TotalCharges  Churn  
0                2              1           29.85        29.85      1  
1                1              2           56.95       1889.5      1  
2                1              2           53.85       108.15      0  
3                1              3           42.30      1840.75      1  
4                2              1           70.70       151.65      0

In [38]:
telecom.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [39]:
telecom.dtypes

gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup         object
DeviceProtection      int64
TechSupport          object
StreamingTV           int64
StreamingMovies      object
Contract              int64
PaperlessBilling     object
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges         object
Churn                 int64
dtype: object

In [40]:
X = telecom.iloc[:, [8, 17]].values
Y = telecom.iloc[:, -1].values

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 42)

In [42]:
X_train

array([[ 1.  , 25.3 ],
       [ 1.  , 75.15],
       [ 0.  , 20.05],
       ...,
       [ 0.  , 21.15],
       [ 1.  , 99.45],
       [ 0.  , 19.8 ]])

In [43]:
Y_train

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [44]:
Y_test

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [45]:
from sklearn.decomposition import PCA

In [46]:
pca = PCA(n_components = 2)

In [47]:
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [48]:
explained_variance = pca.explained_variance_ratio_

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
sc = StandardScaler()

In [51]:
X_train= sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
telecom = lr.fit(X_train, Y_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [53]:
x_pred = telecom.predict(X_train)
y_pred = telecom.predict(X_test)

In [54]:
x_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [55]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score,f1_score

In [57]:
print('Training Accuracy score', accuracy_score(x_pred, Y_train))
print('Testing Accuracy score', accuracy_score(y_pred, Y_test))
print('The training F1 score', f1_score(x_pred, Y_train))
print('The testing F1 score', f1_score(y_pred, Y_test))
print('Precision:',precision_score(Y_test,y_pred))
print('recall:', recall_score(Y_test, y_pred))

Training Accuracy score 0.7357061719045817
Testing Accuracy score 0.7251561612720046
The training F1 score 0.8476315215018555
The testing F1 score 0.8406846609611587
Precision: 0.7272209567198178
recall: 0.9960998439937597


In [58]:
cm = confusion_matrix(Y_test, y_pred)

In [59]:
cm

array([[   0,  479],
       [   5, 1277]], dtype=int64)

In [60]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [61]:
lr = LogisticRegression()

In [62]:
parameteres = {'tol': [0.001, 0.0005, 0.0001], 
               'C': [3, 3, 10]}

In [63]:
gs_cv = GridSearchCV(lr, parameteres, cv=10,
                                      refit = True, n_jobs=-1)

In [64]:
gs_cv.fit(X_test, Y_test)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [3, 3, 10], 'tol': [0.001, 0.0005, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [65]:
print(gs_cv.best_estimator_)

LogisticRegression(C=3, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.001, verbose=0,
                   warm_start=False)


In [66]:
xprediction=gs_cv.predict(X_train)
yprediction=gs_cv.predict(X_test)

In [67]:
print('Training Accuracy score', accuracy_score(xprediction, Y_train))
print('Testing Accuracy score', accuracy_score(yprediction, Y_test))
print('The training F1 score', f1_score(xprediction, Y_train))
print('The testing F1 score', f1_score(yprediction, Y_test))
print('Precision:',precision_score(Y_test,yprediction))
print('recall:', recall_score(Y_test, yprediction))

Training Accuracy score 0.728511927300265
Testing Accuracy score 0.7189097103918228
The training F1 score 0.8416169648774022
The testing F1 score 0.835711915034849
Precision: 0.7273252455228192
recall: 0.9820592823712948


In [71]:
from sklearn.ensemble import AdaBoostClassifier

In [72]:
ada_mod = AdaBoostClassifier(n_estimators=300, learning_rate=0.2)

In [74]:
adaboost = ada_mod.fit(X_train, Y_train)

In [76]:
xpred = adaboost.predict(X_train)
ypred = adaboost.predict(X_test)

In [77]:
print('Training Accuracy score', accuracy_score(xpred, Y_train))
print('Testing Accuracy score', accuracy_score(ypred, Y_test))
print('The training F1 score', f1_score(xpred, Y_train))
print('The testing F1 score', f1_score(ypred, Y_test))
print('Precision:',precision_score(Y_test,ypred))
print('recall:', recall_score(Y_test, ypred))

Training Accuracy score 0.7377887163953049
Testing Accuracy score 0.7268597387847814
The training F1 score 0.8489145849241846
The testing F1 score 0.8418283459388359
Precision: 0.7276861853325753
recall: 0.9984399375975039
